apiVersion: v1
kind: Pod
metadata:
  name: application.blog
  labels:
    name: blog
spec:
  restartPolicy: Never
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    command: ["echo", "Success"]
